# Generated by Django 3.0.4 on 2020-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200402_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='num_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='ratings_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='read_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='started_at',
            field=models.DateField(null=True),
        ),
    ]
