# Generated by Django 3.0.4 on 2020-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200416_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfmodel',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
