# Generated by Django 3.0.4 on 2020-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_shelfmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='location',
            field=models.ManyToManyField(to='books.Locationmodel'),
        ),
    ]
